const HOUR_IN_SECONDS = 3600
const MINUTE_IN_SECONDS = 60
const MAX_SECONDS_VALUE = 86399

const MISSING_INFO = 'missing info'
const CLOSED = 'closed'

const NUMBER_OF_DAYS_IN_A_WEEK = 7

export {
  HOUR_IN_SECONDS,
  MINUTE_IN_SECONDS,
  MAX_SECONDS_VALUE,
  MISSING_INFO,
  CLOSED,
  NUMBER_OF_DAYS_IN_A_WEEK,
}
